services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: ssitizens-frontend
    command: sh ./entrypoint.sh
    environment:
      - VITE_API_URL=http://localhost:8000
      - PORT=8080
    ports:
      - 8080:8080
 