port: 8080

api:
  path: ""

cache:
  default:
    ttl: 300
    checkperiod: 60

redis:
  url:

request:
  sizelimit: "200kb"

logs:
  console:
    active: true
    level: debug
  file:
    active: false
    level: debug
    path: "/files/logs/logs.log"

language:
  allowed:
    - es
    - en
  default: en
  location: "/shared/files/locales"
