# Generated by Django 5.1 on 2025-04-08 13:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('ssitizens', '0001_initial'), ('ssitizens', '0002_useridentification_state'), ('ssitizens', '0003_useridentification_expiration'), ('ssitizens', '0004_alter_issuedverifiablecredential_options_and_more'), ('ssitizens', '0005_alter_profile_address')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='Email')),
                ('address', models.CharField(blank=True, null=True, verbose_name='Address')),
                ('type', models.CharField(choices=[('beneficiary', 'beneficiary'), ('store', 'store')], max_length=100, verbose_name='Type')),
                ('data', models.JSONField(blank=True, null=True, verbose_name='Data')),
                ('terms_accepted', models.BooleanField(default=False, verbose_name='Terms Accepted')),
                ('active_until', models.DateTimeField(blank=True, null=True, verbose_name='Active Until')),
                ('balance', models.FloatField(default=0.0, verbose_name='Balance')),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
        migrations.CreateModel(
            name='PreCodes',
            fields=[
                ('pre_code', models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name='Pre Code')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ssitizens.profile')),
            ],
        ),
        migrations.CreateModel(
            name='IssuedVerifiableCredential',
            fields=[
                ('status', models.BooleanField(default=False, verbose_name='Revocation status')),
                ('vc_id', models.CharField(max_length=4000, primary_key=True, serialize=False, verbose_name='VC Identifier')),
                ('vc_type', models.CharField(max_length=200, verbose_name='VC Type')),
                ('did', models.CharField(max_length=4000, verbose_name='Holder Identifier')),
                ('issuance_date', models.DateTimeField(verbose_name='Issuance Date')),
            ],
            options={
                'verbose_name': 'Issued Verifiable Credential',
                'verbose_name_plural': 'Issued Verifiable Credentials',
            },
        ),
        migrations.CreateModel(
            name='UserIdentification',
            fields=[
                ('session_id', models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name='Session ID')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ssitizens.profile')),
                ('state', models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='State')),
                ('expiration', models.DateTimeField(blank=True, null=True, verbose_name='Expiration')),
            ],
            options={
                'verbose_name': 'User Identification',
                'verbose_name_plural': 'User Identifications',
            },
        ),
    ]
