# Generated by Django 5.1 on 2025-06-03 06:35

import django.db.models.deletion
import ssitizens.enums
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('ssitizens', '0006_remove_profile_balance_profile_active_since_and_more'), ('ssitizens', '0007_alter_transaction_event'), ('ssitizens', '0008_alter_transaction_event'), ('ssitizens', '0009_alter_transaction_event')]

    dependencies = [
        ('ssitizens', '0001_squashed_0005_alter_profile_address'),
        ('ticket_processing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='balance',
        ),
        migrations.AddField(
            model_name='profile',
            name='active_since',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Active Since'),
        ),
        migrations.AddField(
            model_name='profile',
            name='aid_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ticket_processing.aid'),
        ),
        migrations.AddField(
            model_name='profile',
            name='balance_ethers',
            field=models.FloatField(default=0.0, verbose_name='Balance Ethers'),
        ),
        migrations.AddField(
            model_name='profile',
            name='balance_tokens',
            field=models.FloatField(default=0.0, verbose_name='Balance Tokens'),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('event', models.CharField(choices=[('generate', 'generate'), ('transfer', 'transfer'), ('burn', 'burn'), ('forced_burn', 'forcedBurn'), ('assignRole', 'assignRole'), ('deleteRole', 'deleteRole'), ('execution', 'execution')], default=ssitizens.enums.EventType['transfer'], max_length=1000, verbose_name='Event')),
                ('amount_tokens', models.FloatField(default=0.0, verbose_name='Tokens')),
                ('amount_ethers', models.FloatField(default=0.0, verbose_name='Ethers')),
                ('data', models.JSONField(blank=True, null=True, verbose_name='Data')),
                ('hash', models.CharField(verbose_name='Transaction Hash')),
                ('timestamp', models.DateTimeField(blank=True, null=True, verbose_name='Timestamp')),
                ('from_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='From', to='ssitizens.profile')),
                ('to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='To', to='ssitizens.profile')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
            },
        ),
    ]
