# Generated by Django 5.1 on 2025-06-03 07:34

import ssitizens.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssitizens', '0006_remove_profile_balance_profile_active_since_and_more_squashed_0009_alter_transaction_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='event',
            field=models.CharField(choices=[('generate', 'generate'), ('transfer', 'transfer'), ('burn', 'burn'), ('forcedBurn', 'forcedBurn'), ('assignRole', 'assignRole'), ('deleteRole', 'deleteRole'), ('execution', 'execution')], default=ssitizens.enums.EventType['transfer'], max_length=1000, verbose_name='Event'),
        ),
    ]
