# Generated by Django 5.1 on 2025-06-10 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssitizens', '0010_alter_transaction_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='from_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='From', to='ssitizens.profile'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='To', to='ssitizens.profile'),
        ),
    ]
