FROM node:22.6.0-alpine3.20

WORKDIR /app

# Instalar dependencias del sistema
RUN apk add --no-cache git

# Copiar archivos de dependencias
COPY package*.json ./

# Instalar dependencias
RUN npm ci

# Copiar archivos de configuración
COPY tsconfig.json ./

# Copiar código fuente
COPY src ./src

# Compilar TypeScript
RUN npm run compile

# Eliminar dependencias de desarrollo
RUN npm prune --omit=dev

# Configurar entorno de producción
ENV NODE_ENV=production

# Exponer puerto
EXPOSE 8080

# Comando de producción
CMD [ "npm", "run", "start:prod" ]
