# Generated by Django 5.1 on 2025-04-29 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Product Name')),
                ('additional_information', models.CharField(blank=True, null=True, verbose_name='Additional Information')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='Aid',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Aid Name')),
                ('products', models.ManyToManyField(related_name='valid_products', to='ticket_processing.product')),
            ],
            options={
                'verbose_name': 'Aid',
                'verbose_name_plural': 'Aids',
            },
        ),
    ]
