# Generated by Django 5.1 on 2025-05-08 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_processing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='additional_information',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Additional Information'),
        ),
    ]
